### ISSUE TITLE
Core bug in package

### ISSUE THREAD

**Issue by niftylettuce** [danielsen/arf#2]
```sh
Traceback (most recent call last):
  File "_arf.py", line 7, in <module>
    message = load.serialize_report_to_json()
  File "/usr/local/lib/python3.7/site-packages/arf/arf.py", line 122, in serialize_report_to_json
    return json.dumps(serialize_report)
```

https://github.com/danielsen/arf/blob/master/arf/arf.py#L122

This line should be changed as follows (I think):

```diff
    def serialize_report_to_json(self):
        """ Returns the message headers and feedback-report as a JSON string """
-        return json.dumps(serialize_report)
+        return json.dumps(self.serialize_report())
```

**Comment by niftylettuce** [comment]
I've confirmed this fixes the issue.

**Comment by niftylettuce** [comment]
FYI I'm using your package here in a wrapper I made for JavaScript

https://github.com/forwardemail/python-arf

**Comment by danielsen** [comment]
Thanks for the fix. Glad you found the package useful.
